### ISSUE TITLE
Failed to load the Ocamltop-HTML package

### ISSUE THREAD

**Issue by mark-jordalew** [etouss/atom-OcamlTopLevel#2]
[Enter steps to reproduce below:]
1. launch atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [Ocamltop-HTML](https://github.com/tekdreamer/atom-OcamlTopLevel) package, v0.6.0
### Stack Trace

Failed to load the Ocamltop-HTML package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at inherits (/Users/admin/.atom/packages/Ocamltop-HTML/node_modules/atom-message-panel/lib/utils.js:13:28)
    at Object.<anonymous> (/Users/admin/.atom/packages/Ocamltop-HTML/node_modules/atom-message-panel/lib/MessagePanelView.js:18:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/admin/.atom/packages/Ocamltop-HTML/node_modules/atom-message-panel/lib/index.js:2:21)
    at Module._compile (module.js:428:26)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Ocamltop-HTML, v0.6.0
aligner-ruby, v1.4.0
autocomplete-ruby, v0.1.0
language-ocaml, v1.1.2
linter, v1.10.0
linter-rubocop, v0.4.4
linter-ruby, v1.2.0
linter-ruby-reek, v1.3.0
minimap, v4.16.0
ruby-block, v0.3.5
ruby-syntax-replacer, v0.5.1
ruby-test-switcher, v1.2.0

# Dev
No dev packages
```

**Comment by etouss** [comment]
Sorry this package is outdated and i won't fix it.
Please use https://atom.io/packages/repl
Which has kind of same feature.

**Comment by mark-jordalew** [comment]
OK, thanks anyway.
